import Head from "next/head";
import Image from "next/image";
import Dashboard from "../components/Dashboard";
import Login from "../components/Login";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ERA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {" "}
        {/* <Login /> */}
        {/* <Dashboard /> */}
      </main>
    </div>
  );
}
